# Generated by Django 4.0.5 on 2022-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_license_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='park_lot',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='park_state',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
