# Generated by Django 4.0.5 on 2022-06-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_owner_park_lot_owner_park_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='park_lot',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='park_state',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
