# Generated by Django 4.0.5 on 2022-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_license_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='car_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
