# Generated by Django 4.0.5 on 2022-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_users_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='salt',
            field=models.CharField(max_length=100),
        ),
    ]
