# Generated by Django 4.0.5 on 2022-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_users_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
